---

charts:
  - name: qubership-cassandra-operator
    chart_file: charts/helm/cassandra-operator/Chart.yaml
    values_file: charts/helm/cassandra-operator/values.yaml
    image:
      - ghcr.io/netcracker/qubership-cassandra-tests:main