# permissions for end users to view cassandraservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cassandraservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cassandra-operator
    app.kubernetes.io/part-of: cassandra-operator
    app.kubernetes.io/managed-by: kustomize
  name: cassandraservice-viewer-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - cassandraservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - cassandraservices/status
  verbs:
  - get
