# permissions for end users to edit cassandraservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cassandraservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cassandra-operator
    app.kubernetes.io/part-of: cassandra-operator
    app.kubernetes.io/managed-by: kustomize
  name: cassandraservice-editor-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - cassandraservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubership.org
  resources:
  - cassandraservices/status
  verbs:
  - get
