# permissions for end users to view cassandras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cassandra-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cassandra-operator
    app.kubernetes.io/part-of: cassandra-operator
    app.kubernetes.io/managed-by: kustomize
  name: cassandra-viewer-role
rules:
- apiGroups:
  - qubership.org.qubership.org
  resources:
  - cassandras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qubership.org.qubership.org
  resources:
  - cassandras/status
  verbs:
  - get
