## Append samples you want in your CSV to this file as resources ##
resources:
- qubership.org_v1_cassandraservice.yaml
- qubership.org_v1alpha1_cassandra.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
