## Append samples you want in your CSV to this file as resources ##
resources:
- netcracker.com_v1_cassandraservice.yaml
- netcracker.com_v1alpha1_cassandra.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
