apiVersion: qubership.org.qubership.org/v1alpha1
kind: Cassandra
metadata:
  labels:
    app.kubernetes.io/name: cassandra
    app.kubernetes.io/instance: cassandra-sample
    app.kubernetes.io/part-of: cassandra-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cassandra-operator
  name: cassandra-sample
spec:
  # TODO(user): Add fields here
