apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "credentials-saver-%s" (lower (randAlphaNum 5)) }}
  labels: {{- include "cassandra.defaultLabels" . | trim | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: "credentials-saver"
      labels: {{- include "cassandra.defaultLabels" . | trim | nindent 8 }}
    spec:
      restartPolicy: Never
      serviceAccountName: hook-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: credentials-saver
        image: {{ template "find_image" (dict "deployName" "operator_init" "SERVICE_NAME" "operator_init" "vals" .Values "default" .Values.operator.initImage) }}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
          - name: SECRET_NAMES
            value: {{ .Values.cassandra.secretName }}
          - name: IS_HOOK
            value: "True"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.operator.resources | nindent 10 }}