apiVersion: v1
kind: ServiceAccount
metadata:
  name: hook-sa
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
