{{- if .Values.reaper.install }}
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-truststore-reaper-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cassandra.defaultLabels" . | nindent 4 }}
stringData:
  password: {{ .Values.reaper.truststorePassword | quote }}
type: Opaque
{{ end }}