{{- if  (.Values.reaper.install) }}
 {{- if .Values.CLOUD_PUBLIC_HOST }}
 {{template "nosql.core.secret.internal" (dict "values" . "vltEnabled" .Values.vaultRegistration.enabled "vltPath" (printf "nc-%s_%s" .Values.CLOUD_PUBLIC_HOST .Release.Namespace ) "secret" .Values.reaper)}}
 {{ else }}
 {{template "nosql.core.secret.internal" (dict "values" . "vltEnabled" .Values.vaultRegistration.enabled "vltPath" .Values.vaultRegistration.path "secret" .Values.reaper)}}
 {{ end }}
{{ end }}